<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="Publication.aspx.cs" Inherits="LibrarySystem.PublicationPL" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
    <style type="text/css">
        .style1 {
            width: 361px;
        }

        .style2 {
            width: 691px;
        }

        .style3 {
            width: 291px;
        }
    </style>

      <script src="../js/jquery-1.9.1.min.js" type="text/javascript"></script>
     <script type="text/javascript"> 
         function Validate() {
             var status = true;
             var msg = '';

          
             if ($('#<%=txtpub.ClientID%>').val() == "") {
                 msg += 'Please enter Publication Name!\n';
                 status = false;
             }

          
             if (status == false) {
                 alert(msg);
                 return false;
             }
             else {

              return true;
             }



         }




     </script>

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <table class="tbl">
        <tr>
            <td class="tblhead">ADD NEW PUBLICATION</td>
        </tr>
        <tr>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>
                <table align="center" width="700">
                    <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td class="lbl">Publication Name :
                        </td>
                        <td>
                            <asp:TextBox ID="txtpub" runat="server" CssClass="txt"></asp:TextBox>
                            
                        </td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td>
                            <asp:Button ID="btnadd" runat="server" CssClass="btn" onclick="btnadd_Click"
                                Text="ADD Publication" OnClientClick="return Validate();" />
                        </td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td>
                            <asp:Label ID="lblmsg" runat="server" CssClass="lbl" ForeColor="Black"></asp:Label>
                        </td>
                    </tr>
                </table>
                <br />
                <table class="style2">
                    <tr>
                        <td class="style3">&nbsp;</td>
                        <td>
                            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False"
                                AutoGenerateDeleteButton="True" CellPadding="2"
                                DataKeyNames="pid" ForeColor="Black" GridLines="None"
                                onrowcancelingedit="GridView1_RowCancelingEdit"
                                onrowediting="GridView1_RowEditing"
                                 onrowupdating="GridView1_RowUpdating" 
                                 onrowdeleting="GridView1_RowDeleting"

                                BackColor="LightGoldenrodYellow"
                                                          BorderColor="Tan" BorderWidth="1px">
                                <alternatingrowstyle backcolor="PaleGoldenrod" />
                                <columns>
                                    <asp:CommandField CausesValidation="false" ShowEditButton="true" />
                                    <asp:BoundField DataField="PublicationName" HeaderText="Publication" />
                                </columns>
                                <footerstyle backcolor="Tan" />
                                <headerstyle backcolor="#FF6600" font-bold="True" />
                                <pagerstyle backcolor="PaleGoldenrod" forecolor="DarkSlateBlue"
                                    horizontalalign="Center" />
                                <selectedrowstyle backcolor="DarkSlateBlue" forecolor="GhostWhite" />
                                <sortedascendingcellstyle backcolor="#FAFAE7" />
                                <sortedascendingheaderstyle backcolor="#DAC09E" />
                                <sorteddescendingcellstyle backcolor="#E1DB9C" />
                                <sorteddescendingheaderstyle backcolor="#C2A47B" />
                            </asp:GridView>
                        </td>
                    </tr>
                    <tr>
                        <td class="style3">&nbsp;</td>
                        <td>&nbsp;</td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</asp:Content>


